CONFIG:
  EMBEDDING_MODEL_NAME: thenlper/gte-large
  DATA_DIR: /mnt/c/Users/heman/Desktop/Coding/md/
  CHUNK_SIZE: 512
  NUM_SIMILAR: 5  # Number of similar documents to retrieve
  LLM_MODEL: gpt-4o-mini
  QUERY: Initialize ModelLoader with a ModelConfig instanceparam model_config An instance of ModelConfig with model details.
    
